---
title: "complaints_2022"
author: "Jiashu Liu"
date: "2024-03-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load Data
# NYPD complaint data in year 2022, filtered by CMPLNT_FR_DT 
# CMPLNT_FR_DT is the exact date of occurrence for the reported event. In other words, the starting date of the occurrence.
library(readr)
NYPD_Complaint_2022 <- read_csv("../crime_data/NYPD_Complaint_2022.csv")
```
```{r}
# Load libraries
library(tidyverse)
library(dplyr)
library(ggplot2)
library(lubridate)
library(sf)
library(tigris)
library(gt) # for better table format
library(plotly) # for interactive plot
```

```{r}
# Data Cleaning 
complaint_2022 <- NYPD_Complaint_2022 %>% 
  select(-c(PARKS_NM, TRANSIT_DISTRICT, HADEVELOPT, HOUSING_PSA, STATION_NAME)) %>% 
  filter(VIC_RACE != "UNKNOWN" & VIC_RACE!= "(null)")
# write.csv(complaint_2022, "complaint_2022.csv")
```

```{r}
# Victim race summary table 
race_summary_table <- complaint_2022 %>% 
  group_by(VIC_RACE) %>% 
  summarise(Count = n()) %>% 
  arrange(desc(Count))

gt(race_summary_table)

# Level of offense summary table 
# Level of offense: felony, misdemeanor, violatio
offence_summary_table <- complaint_2022 %>% 
  group_by(LAW_CAT_CD) %>% 
  summarise(Count = n()) %>% 
  arrange(desc(Count))
gt(offence_summary_table)
```
```{r}
# Daily trend (asian/pacific islander)
asian_2022_daily <- complaint_2022 %>% 
  mutate(CMPLNT_FR_DT = as.Date(CMPLNT_FR_DT, format = "%m/%d/%Y")) %>% 
  filter(VIC_RACE == "ASIAN / PACIFIC ISLANDER") %>% 
  group_by(CMPLNT_FR_DT) %>% 
  summarise(num_vic = n())

# plot the data (line plot)
asian_2022_daily_plot <- asian_2022_daily %>% 
  ggplot(aes(x = CMPLNT_FR_DT, y = num_vic))+
  geom_line()+
  labs(title = "Daily Number of Victims for ASIAN / PACIFIC ISLANDER in 2022", x = "Date", y = "Number of Victims") +
  theme_minimal()
asian_2022_daily_plot

# Monthly trend (asian/pacific islander)
asian_2022_monthly <- asian_2022_daily %>% 
  mutate(CMPLNT_FR_DT = as.Date(CMPLNT_FR_DT, format = "%m/%d/%Y"),
         Month = factor(format(CMPLNT_FR_DT, "%b"), levels = month.abb)) %>% 
  group_by(Month) %>% 
  summarise(Monthly_Count = sum(num_vic)) %>% 
  ggplot(aes(x = Month, y = Monthly_Count))+
  geom_col(fill = "darkblue")+
   labs(title = "Monthly Counts of Victims for ASIAN / PACIFIC ISLANDER in 2022",
       x = "Month",
       y = "Number of Victims") + 
  theme_minimal()

asian22_monthly <- ggplotly(asian_2022_monthly)
asian22_monthly
```

```{r}
# Daily trend (black)
black_2022_daily <- complaint_2022 %>% 
  mutate(CMPLNT_FR_DT = as.Date(CMPLNT_FR_DT, format = "%m/%d/%Y")) %>% 
  filter(VIC_RACE == "BLACK") %>% 
  group_by(CMPLNT_FR_DT) %>% 
  summarise(num_vic = n())

# plot the data (line plot)
black_2022_daily_plot <- black_2022_daily %>% 
  ggplot(aes(x = CMPLNT_FR_DT, y = num_vic))+
  geom_line()+
  labs(title = "Daily Number of Victims for BLACK in 2022", x = "Date", y = "Number of Victims") +
  theme_minimal()
black_2022_daily_plot

# Monthly trend (black)
black_2022_monthly <- black_2022_daily %>% 
  mutate(CMPLNT_FR_DT = as.Date(CMPLNT_FR_DT, format = "%m/%d/%Y"),
         Month = factor(format(CMPLNT_FR_DT, "%b"), levels = month.abb)) %>% 
  group_by(Month) %>% 
  summarise(Monthly_Count = sum(num_vic)) %>% 
  ggplot(aes(x = Month, y = Monthly_Count))+
  geom_col(fill = "lightpink")+
   labs(title = "Monthly Counts of Victims for BLACK in 2022",
       x = "Month",
       y = "Number of Victims") + 
  theme_minimal()

black22_monthly <- ggplotly(black_2022_monthly)
black22_monthly
```
















